sudo: required
language: node_js
node_js:
  - "6.10.1"
install:
  - npm install
script:
  - npm run ci
deploy:
    provider: heroku
    api_key:
        secure: "f912566d-7941-4432-943f-77748e799067"
    